name: FusionPixelmon
version: 1.9
author: BrendonCurmi
main: me.fusiondev.fusionpixelmon.spigot.SpigotFusionPixelmon
website: https://github.com/BrendonCurmi/FusionPixelmon
commands:
  pd:
    description: Opens the PokeDesigner inventory
    permission: fusionpixelmon.command.pokedesigner
    aliases: [pokedesigner]
  arc:
    description: Opens the ArcPlate inventory
    permission: fusionpixelmon.command.arc
  pokemodifier:
    description: Gives a Pokemon modifier to the player
    permission: fusionpixelmon.command.admin.pokemodifiers
