name: FusionPixelmon
version: 1.10
author: FusionDev
description: Add a little extra to your Pixelmon experience - PokeBuilder, ArcPlates, Modifier Tokens, and more!
main: me.fusiondev.fusionpixelmon.spigot.SpigotFusionPixelmon
website: https://github.com/BrendonCurmi/FusionPixelmon
commands:
  pd:
    description: Opens the PokeDesigner inventory
    permission: fusionpixelmon.command.pokedesigner
    aliases: [pokedesigner]
  arc:
    description: Opens the ArcPlate inventory
    permission: fusionpixelmon.command.arc
  pokemodifier:
    description: Gives a Pokemon modifier to the player
    permission: fusionpixelmon.command.admin.pokemodifier
